name: Build

on:
  push:
  pull_request:
  # schedule:
  #   - cron: "0 0 * * *" # This value corresponds to 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: example-application

      - name: Initialize
        working-directory: example-application

        # Initialize the west workspace. The '-l' option means to use the current directory as the manifest repository.
        # Update the west workspace. The '-o=--depth=1' option is used to limit the history of the cloned repositories 
        # to the last commit, which can save time and disk space. The '-n' option is used to only fetch the manifest-referenced
        # repositories but not check them out.
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: example-application
        run: |
          west twister -T samples/app -v --inline-logs --integration

      - name: Twister Tests
        working-directory: example-application
        run: |
          west twister -T tests --integration
